<?php
/**
 * UserFrosting (http://www.userfrosting.com)
 *
 * @link      https://github.com/userfrosting/UserFrosting
 * @license   https://github.com/userfrosting/UserFrosting/blob/master/licenses/UserFrosting.md (MIT License)
 */
namespace UserFrosting\Sprinkle\Portal\Database\Migrations\v010;

use Illuminate\Database\Schema\Blueprint;
use UserFrosting\Sprinkle\Portal\Database\Models\Country;
use UserFrosting\System\Bakery\Migration;

/**
 * Countries table migration
 *
 * Version 0.1.0
 *
 * @author Kai Schröer (https://schroeer.co)
 * @see https://laravel.com/docs/5.4/migrations#tables
 */
class CountriesTable extends Migration
{
    /**
     * {@inheritDoc}
     */
    public function up()
    {
        if (!$this->schema->hasTable('countries')) {
            $this->schema->create('countries', function (Blueprint $table) {
                $table->increments('id');
                $table->string('code')->nullable(false)->unique();
                $table->string('name')->nullable(false);

                $table->engine = 'InnoDB';
                $table->collation = 'utf8_unicode_ci';
                $table->charset = 'utf8';
            });

            $countries = [
                new Country(['code' => 'AF', 'name' => 'Afghanistan']),
                new Country(['code' => 'AL', 'name' => 'Albania']),
                new Country(['code' => 'DZ', 'name' => 'Algeria']),
                new Country(['code' => 'DS', 'name' => 'American Samoa']),
                new Country(['code' => 'AD', 'name' => 'Andorra']),
                new Country(['code' => 'AO', 'name' => 'Angola']),
                new Country(['code' => 'AI', 'name' => 'Anguilla']),
                new Country(['code' => 'AQ', 'name' => 'Antarctica']),
                new Country(['code' => 'AG', 'name' => 'Antigua and Barbuda']),
                new Country(['code' => 'AR', 'name' => 'Argentina']),
                new Country(['code' => 'AM', 'name' => 'Armenia']),
                new Country(['code' => 'AW', 'name' => 'Aruba']),
                new Country(['code' => 'AU', 'name' => 'Australia']),
                new Country(['code' => 'AT', 'name' => 'Austria']),
                new Country(['code' => 'AZ', 'name' => 'Azerbaijan']),
                new Country(['code' => 'BS', 'name' => 'Bahamas']),
                new Country(['code' => 'BH', 'name' => 'Bahrain']),
                new Country(['code' => 'BD', 'name' => 'Bangladesh']),
                new Country(['code' => 'BB', 'name' => 'Barbados']),
                new Country(['code' => 'BY', 'name' => 'Belarus']),
                new Country(['code' => 'BE', 'name' => 'Belgium']),
                new Country(['code' => 'BZ', 'name' => 'Belize']),
                new Country(['code' => 'BJ', 'name' => 'Benin']),
                new Country(['code' => 'BM', 'name' => 'Bermuda']),
                new Country(['code' => 'BT', 'name' => 'Bhutan']),
                new Country(['code' => 'BO', 'name' => 'Bolivia']),
                new Country(['code' => 'BA', 'name' => 'Bosnia and Herzegovina']),
                new Country(['code' => 'BW', 'name' => 'Botswana']),
                new Country(['code' => 'BV', 'name' => 'Bouvet Island']),
                new Country(['code' => 'BR', 'name' => 'Brazil']),
                new Country(['code' => 'IO', 'name' => 'British Indian Ocean Territory']),
                new Country(['code' => 'BN', 'name' => 'Brunei Darussalam']),
                new Country(['code' => 'BG', 'name' => 'Bulgaria']),
                new Country(['code' => 'BF', 'name' => 'Burkina Faso']),
                new Country(['code' => 'BI', 'name' => 'Burundi']),
                new Country(['code' => 'KH', 'name' => 'Cambodia']),
                new Country(['code' => 'CM', 'name' => 'Cameroon']),
                new Country(['code' => 'CA', 'name' => 'Canada']),
                new Country(['code' => 'CV', 'name' => 'Cape Verde']),
                new Country(['code' => 'KY', 'name' => 'Cayman Islands']),
                new Country(['code' => 'CF', 'name' => 'Central African Republic']),
                new Country(['code' => 'TD', 'name' => 'Chad']),
                new Country(['code' => 'CL', 'name' => 'Chile']),
                new Country(['code' => 'CN', 'name' => 'China']),
                new Country(['code' => 'CX', 'name' => 'Christmas Island']),
                new Country(['code' => 'CC', 'name' => 'Cocos (Keeling) Islands']),
                new Country(['code' => 'CO', 'name' => 'Colombia']),
                new Country(['code' => 'KM', 'name' => 'Comoros']),
                new Country(['code' => 'CG', 'name' => 'Congo']),
                new Country(['code' => 'CK', 'name' => 'Cook Islands']),
                new Country(['code' => 'CR', 'name' => 'Costa Rica']),
                new Country(['code' => 'HR', 'name' => 'Croatia (Hrvatska)']),
                new Country(['code' => 'CU', 'name' => 'Cuba']),
                new Country(['code' => 'CY', 'name' => 'Cyprus']),
                new Country(['code' => 'CZ', 'name' => 'Czech Republic']),
                new Country(['code' => 'DK', 'name' => 'Denmark']),
                new Country(['code' => 'DJ', 'name' => 'Djibouti']),
                new Country(['code' => 'DM', 'name' => 'Dominica']),
                new Country(['code' => 'DO', 'name' => 'Dominican Republic']),
                new Country(['code' => 'TP', 'name' => 'East Timor']),
                new Country(['code' => 'EC', 'name' => 'Ecuador']),
                new Country(['code' => 'EG', 'name' => 'Egypt']),
                new Country(['code' => 'SV', 'name' => 'El Salvador']),
                new Country(['code' => 'GQ', 'name' => 'Equatorial Guinea']),
                new Country(['code' => 'ER', 'name' => 'Eritrea']),
                new Country(['code' => 'EE', 'name' => 'Estonia']),
                new Country(['code' => 'ET', 'name' => 'Ethiopia']),
                new Country(['code' => 'FK', 'name' => 'Falkland Islands (Malvinas)']),
                new Country(['code' => 'FO', 'name' => 'Faroe Islands']),
                new Country(['code' => 'FJ', 'name' => 'Fiji']),
                new Country(['code' => 'FI', 'name' => 'Finland']),
                new Country(['code' => 'FR', 'name' => 'France']),
                new Country(['code' => 'FX', 'name' => 'France, Metropolitan']),
                new Country(['code' => 'GF', 'name' => 'French Guiana']),
                new Country(['code' => 'PF', 'name' => 'French Polynesia']),
                new Country(['code' => 'TF', 'name' => 'French Southern Territories']),
                new Country(['code' => 'GA', 'name' => 'Gabon']),
                new Country(['code' => 'GM', 'name' => 'Gambia']),
                new Country(['code' => 'GE', 'name' => 'Georgia']),
                new Country(['code' => 'DE', 'name' => 'Germany']),
                new Country(['code' => 'GH', 'name' => 'Ghana']),
                new Country(['code' => 'GI', 'name' => 'Gibraltar']),
                new Country(['code' => 'GK', 'name' => 'Guernsey']),
                new Country(['code' => 'GR', 'name' => 'Greece']),
                new Country(['code' => 'GL', 'name' => 'Greenland']),
                new Country(['code' => 'GD', 'name' => 'Grenada']),
                new Country(['code' => 'GP', 'name' => 'Guadeloupe']),
                new Country(['code' => 'GU', 'name' => 'Guam']),
                new Country(['code' => 'GT', 'name' => 'Guatemala']),
                new Country(['code' => 'GN', 'name' => 'Guinea']),
                new Country(['code' => 'GW', 'name' => 'Guinea-Bissau']),
                new Country(['code' => 'GY', 'name' => 'Guyana']),
                new Country(['code' => 'HT', 'name' => 'Haiti']),
                new Country(['code' => 'HM', 'name' => 'Heard and Mc Donald Islands']),
                new Country(['code' => 'HN', 'name' => 'Honduras']),
                new Country(['code' => 'HK', 'name' => 'Hong Kong']),
                new Country(['code' => 'HU', 'name' => 'Hungary']),
                new Country(['code' => 'IS', 'name' => 'Iceland']),
                new Country(['code' => 'IN', 'name' => 'India']),
                new Country(['code' => 'IM', 'name' => 'Isle of Man']),
                new Country(['code' => 'ID', 'name' => 'Indonesia']),
                new Country(['code' => 'IR', 'name' => 'Iran (Islamic Republic of)']),
                new Country(['code' => 'IQ', 'name' => 'Iraq']),
                new Country(['code' => 'IE', 'name' => 'Ireland']),
                new Country(['code' => 'IL', 'name' => 'Israel']),
                new Country(['code' => 'IT', 'name' => 'Italy']),
                new Country(['code' => 'CI', 'name' => 'Ivory Coast']),
                new Country(['code' => 'JE', 'name' => 'Jersey']),
                new Country(['code' => 'JM', 'name' => 'Jamaica']),
                new Country(['code' => 'JP', 'name' => 'Japan']),
                new Country(['code' => 'JO', 'name' => 'Jordan']),
                new Country(['code' => 'KZ', 'name' => 'Kazakhstan']),
                new Country(['code' => 'KE', 'name' => 'Kenya']),
                new Country(['code' => 'KI', 'name' => 'Kiribati']),
                new Country(['code' => 'KP', 'name' => 'Democratic People\'s Republic of Korea']),
                new Country(['code' => 'KR', 'name' => 'Republic of Korea']),
                new Country(['code' => 'XK', 'name' => 'Kosovo']),
                new Country(['code' => 'KW', 'name' => 'Kuwait']),
                new Country(['code' => 'KG', 'name' => 'Kyrgyzstan']),
                new Country(['code' => 'LA', 'name' => 'Lao People\'s Democratic Republic']),
                new Country(['code' => 'LV', 'name' => 'Latvia']),
                new Country(['code' => 'LB', 'name' => 'Lebanon']),
                new Country(['code' => 'LS', 'name' => 'Lesotho']),
                new Country(['code' => 'LR', 'name' => 'Liberia']),
                new Country(['code' => 'LY', 'name' => 'Libyan Arab Jamahiriya']),
                new Country(['code' => 'LI', 'name' => 'Liechtenstein']),
                new Country(['code' => 'LT', 'name' => 'Lithuania']),
                new Country(['code' => 'LU', 'name' => 'Luxembourg']),
                new Country(['code' => 'MO', 'name' => 'Macau']),
                new Country(['code' => 'MK', 'name' => 'Macedonia']),
                new Country(['code' => 'MG', 'name' => 'Madagascar']),
                new Country(['code' => 'MW', 'name' => 'Malawi']),
                new Country(['code' => 'MY', 'name' => 'Malaysia']),
                new Country(['code' => 'MV', 'name' => 'Maldives']),
                new Country(['code' => 'ML', 'name' => 'Mali']),
                new Country(['code' => 'MT', 'name' => 'Malta']),
                new Country(['code' => 'MH', 'name' => 'Marshall Islands']),
                new Country(['code' => 'MQ', 'name' => 'Martinique']),
                new Country(['code' => 'MR', 'name' => 'Mauritania']),
                new Country(['code' => 'MU', 'name' => 'Mauritius']),
                new Country(['code' => 'TY', 'name' => 'Mayotte']),
                new Country(['code' => 'MX', 'name' => 'Mexico']),
                new Country(['code' => 'FM', 'name' => 'Federated States of Micronesia']),
                new Country(['code' => 'MD', 'name' => 'Republic of Moldova']),
                new Country(['code' => 'MC', 'name' => 'Monaco']),
                new Country(['code' => 'MN', 'name' => 'Mongolia']),
                new Country(['code' => 'ME', 'name' => 'Montenegro']),
                new Country(['code' => 'MS', 'name' => 'Montserrat']),
                new Country(['code' => 'MA', 'name' => 'Morocco']),
                new Country(['code' => 'MZ', 'name' => 'Mozambique']),
                new Country(['code' => 'MM', 'name' => 'Myanmar']),
                new Country(['code' => 'NA', 'name' => 'Namibia']),
                new Country(['code' => 'NR', 'name' => 'Nauru']),
                new Country(['code' => 'NP', 'name' => 'Nepal']),
                new Country(['code' => 'NL', 'name' => 'Netherlands']),
                new Country(['code' => 'AN', 'name' => 'Netherlands Antilles']),
                new Country(['code' => 'NC', 'name' => 'New Caledonia']),
                new Country(['code' => 'NZ', 'name' => 'New Zealand']),
                new Country(['code' => 'NI', 'name' => 'Nicaragua']),
                new Country(['code' => 'NE', 'name' => 'Niger']),
                new Country(['code' => 'NG', 'name' => 'Nigeria']),
                new Country(['code' => 'NU', 'name' => 'Niue']),
                new Country(['code' => 'NF', 'name' => 'Norfolk Island']),
                new Country(['code' => 'MP', 'name' => 'Northern Mariana Islands']),
                new Country(['code' => 'NO', 'name' => 'Norway']),
                new Country(['code' => 'OM', 'name' => 'Oman']),
                new Country(['code' => 'PK', 'name' => 'Pakistan']),
                new Country(['code' => 'PW', 'name' => 'Palau']),
                new Country(['code' => 'PS', 'name' => 'Palestine']),
                new Country(['code' => 'PA', 'name' => 'Panama']),
                new Country(['code' => 'PG', 'name' => 'Papua New Guinea']),
                new Country(['code' => 'PY', 'name' => 'Paraguay']),
                new Country(['code' => 'PE', 'name' => 'Peru']),
                new Country(['code' => 'PH', 'name' => 'Philippines']),
                new Country(['code' => 'PN', 'name' => 'Pitcairn']),
                new Country(['code' => 'PL', 'name' => 'Poland']),
                new Country(['code' => 'PT', 'name' => 'Portugal']),
                new Country(['code' => 'PR', 'name' => 'Puerto Rico']),
                new Country(['code' => 'QA', 'name' => 'Qatar']),
                new Country(['code' => 'RE', 'name' => 'Reunion']),
                new Country(['code' => 'RO', 'name' => 'Romania']),
                new Country(['code' => 'RU', 'name' => 'Russian Federation']),
                new Country(['code' => 'RW', 'name' => 'Rwanda']),
                new Country(['code' => 'KN', 'name' => 'Saint Kitts and Nevis']),
                new Country(['code' => 'LC', 'name' => 'Saint Lucia']),
                new Country(['code' => 'VC', 'name' => 'Saint Vincent and the Grenadines']),
                new Country(['code' => 'WS', 'name' => 'Samoa']),
                new Country(['code' => 'SM', 'name' => 'San Marino']),
                new Country(['code' => 'ST', 'name' => 'Sao Tome and Principe']),
                new Country(['code' => 'SA', 'name' => 'Saudi Arabia']),
                new Country(['code' => 'SN', 'name' => 'Senegal']),
                new Country(['code' => 'RS', 'name' => 'Serbia']),
                new Country(['code' => 'SC', 'name' => 'Seychelles']),
                new Country(['code' => 'SL', 'name' => 'Sierra Leone']),
                new Country(['code' => 'SG', 'name' => 'Singapore']),
                new Country(['code' => 'SK', 'name' => 'Slovakia']),
                new Country(['code' => 'SI', 'name' => 'Slovenia']),
                new Country(['code' => 'SB', 'name' => 'Solomon Islands']),
                new Country(['code' => 'SO', 'name' => 'Somalia']),
                new Country(['code' => 'ZA', 'name' => 'South Africa']),
                new Country(['code' => 'GS', 'name' => 'South Georgia South Sandwich Islands']),
                new Country(['code' => 'ES', 'name' => 'Spain']),
                new Country(['code' => 'LK', 'name' => 'Sri Lanka']),
                new Country(['code' => 'SH', 'name' => 'St. Helena']),
                new Country(['code' => 'PM', 'name' => 'St. Pierre and Miquelon']),
                new Country(['code' => 'SD', 'name' => 'Sudan']),
                new Country(['code' => 'SR', 'name' => 'Suriname']),
                new Country(['code' => 'SJ', 'name' => 'Svalbard and Jan Mayen Islands']),
                new Country(['code' => 'SZ', 'name' => 'Swaziland']),
                new Country(['code' => 'SE', 'name' => 'Sweden']),
                new Country(['code' => 'CH', 'name' => 'Switzerland']),
                new Country(['code' => 'SY', 'name' => 'Syrian Arab Republic']),
                new Country(['code' => 'TW', 'name' => 'Taiwan']),
                new Country(['code' => 'TJ', 'name' => 'Tajikistan']),
                new Country(['code' => 'TZ', 'name' => 'United Republic of Tanzania']),
                new Country(['code' => 'TH', 'name' => 'Thailand']),
                new Country(['code' => 'TG', 'name' => 'Togo']),
                new Country(['code' => 'TK', 'name' => 'Tokelau']),
                new Country(['code' => 'TO', 'name' => 'Tonga']),
                new Country(['code' => 'TT', 'name' => 'Trinidad and Tobago']),
                new Country(['code' => 'TN', 'name' => 'Tunisia']),
                new Country(['code' => 'TR', 'name' => 'Turkey']),
                new Country(['code' => 'TM', 'name' => 'Turkmenistan']),
                new Country(['code' => 'TC', 'name' => 'Turks and Caicos Islands']),
                new Country(['code' => 'TV', 'name' => 'Tuvalu']),
                new Country(['code' => 'UG', 'name' => 'Uganda']),
                new Country(['code' => 'UA', 'name' => 'Ukraine']),
                new Country(['code' => 'AE', 'name' => 'United Arab Emirates']),
                new Country(['code' => 'GB', 'name' => 'United Kingdom']),
                new Country(['code' => 'US', 'name' => 'United States']),
                new Country(['code' => 'UM', 'name' => 'United States minor outlying islands']),
                new Country(['code' => 'UY', 'name' => 'Uruguay']),
                new Country(['code' => 'UZ', 'name' => 'Uzbekistan']),
                new Country(['code' => 'VU', 'name' => 'Vanuatu']),
                new Country(['code' => 'VA', 'name' => 'Vatican City State']),
                new Country(['code' => 'VE', 'name' => 'Venezuela']),
                new Country(['code' => 'VN', 'name' => 'Vietnam']),
                new Country(['code' => 'VG', 'name' => 'Virgin Islands (British)']),
                new Country(['code' => 'VI', 'name' => 'Virgin Islands (U.S.)']),
                new Country(['code' => 'WF', 'name' => 'Wallis and Futuna Islands']),
                new Country(['code' => 'EH', 'name' => 'Western Sahara']),
                new Country(['code' => 'YE', 'name' => 'Yemen']),
                new Country(['code' => 'YU', 'name' => 'Yugoslavia']),
                new Country(['code' => 'ZR', 'name' => 'Zaire']),
                new Country(['code' => 'ZM', 'name' => 'Zambia']),
                new Country(['code' => 'ZW', 'name' => 'Zimbabwe'])
            ];

            foreach ($countries as $country) {
                $country->save();
            }
        }
    }

    /**
     * {@inheritDoc}
     */
    public function down()
    {
        $this->schema->drop('countries');
    }
}
